name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install and Build
        run: |
          npm ci
          npx ng build --base-href /tocxx.github.io/
      - name: Copy index to 404
        run: cp dist/tocxxio/browser/index.html dist/tocxxio/browser/404.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/tocxxio/browser

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
